[package]
name = "port-scan"
version = "0.1.3"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.18.0"
tokio = {version = "1.47.1", features = ["full"]}